### ISSUE TITLE
Keyboard not supported

### ISSUE THREAD

**Issue by artenbe** [ojacques/SynthesiaKontrol#12]
Hi,

I get the following error, not matter which keyboard I select: 
Select your keyboard (*1,2,3,4):
  1-Komplete Kontrol S61 MK2
  2-Komplete Kontrol S88 MK2
  3-Komplete Kontrol S61 MK1
  4-Komplete Kontrol S88 MK1
4
Sorry, keyboard not supported yet!

I have a s61mk1, it's in midi mode and everything else is like it hsould be according to your steps so I'm wondering why it doesn't work?

**Comment by ojacques** [comment]
@artenbe - the code for S61 MK1 was in GIT / master but not in executable (v1.1). Can you check with [release v1.2](https://github.com/ojacques/SynthesiaKontrol/releases/tag/v1.2) (that is, if you are on Windows) and let me know if that works?

**Comment by ojacques** [comment]
Closing, with no answer. Hopefully this works as expected for S61 MK1 with v1.2 onwards.
