### ISSUE TITLE
module 'hid' has no attribute 'device'  (macOS)

### ISSUE THREAD

**Issue by joshstovall** [ojacques/SynthesiaKontrol#13]
I am trying to get this working on macOS, and get this message.
Any suggestions for a solution?
```
python3 SynthesiaKontrol.py

Select your keyboard (1,2,3,...):
  1-Komplete Kontrol S61 MK2
  2-Komplete Kontrol S88 MK2
  3-Komplete Kontrol S49 MK2
  4-Komplete Kontrol S61 MK1
  5-Komplete Kontrol S88 MK1
  6-Komplete Kontrol S49 MK1
  7-Komplete Kontrol S25 MK1
3
Connecting to Komplete Kontrol Keyboard
Opening Keyboard device...
Traceback (most recent call last):
  File "SynthesiaKontrol.py", line 224, in <module>
    connected = init()
  File "SynthesiaKontrol.py", line 24, in init
    device=hid.device()
AttributeError: module 'hid' has no attribute 'device'
```

**Comment by AlFalahTaieb** [comment]
Did you try to run it as root ? 

sudo python3 SynthesiaKontrol.py

**Comment by ojacques** [comment]
@joshstovall - per [this video](https://www.youtube.com/watch?v=8fCx9_58kjU) from someone who uses a MAC, this seems to work:
![image](https://user-images.githubusercontent.com/5385290/74382146-20bbfc00-4ded-11ea-8599-ae80622f7f06.png)

Did you use the "pip install" commands per [this](https://github.com/ojacques/SynthesiaKontrol#synthesiakontrol-1)?

**Comment by jonlambert** [comment]
FWIW I'm running into this issue too at the moment. I've installed pip dependancies, and hidapi (via Homebrew). 

Running as root yields the same:

```
AttributeError: module 'hid' has no attribute 'device'
```

macOS Version: 10.14.6
Python Version: Python 3.7.7

**Comment by jonlambert** [comment]
I've tracked down the problem. I had another `hid` library installed, so running:

```
pip3 uninstall hid && pip3 install -r requirements.txt
```

This fixed the issue for me!
