### ISSUE TITLE
Komplete Kontrol S88 MK2 not supported on MacOS

### ISSUE THREAD

**Issue by Tetrikus** [ojacques/SynthesiaKontrol#16]
Thanks for this script! I was super happy to find this!

But I get the error, that the S88 MK2 (and MK1) is not yet supported. Not sure, whether this is a bug or just a feature which is yet missing? Could you clarify?

**Comment by Tetrikus** [comment]
I just noticed, that I get this message, no matter what keyboard I choose in the list. 🤔

**Comment by ojacques** [comment]
Maybe you typed something different than a number, then enter. The error message was not clear: I improved it.
