### ISSUE TITLE
-bash: pip: command not found

### ISSUE THREAD

**Issue by basecrest** [ojacques/SynthesiaKontrol#18]
Hello,

I'm following the steps and this is as far as i can go.

Mansfields-MacBook-Pro:~ Mansfield$ pip install hidapi
-bash: pip: command not found

Any suggestions to finding a solution?

Thanks
Nathan

**Comment by ojacques** [comment]
@basecrest - if you have Python3 installed (which is now required), you may have to use `pip3` instead of `pip`. Let me update the doc.

**Comment by basecrest** [comment]
Hello Oliver,
Thanks so much for sharing this project. I learn about adding 3 to the command line "python 3....

I'm presently trying to figure out the following at the install the KK Light Guide python files....

Mansfields-MacBook-Pro:KompleteKontrolLightGuide-master Mansfield$ python3 SynthesiaKontrol-MK1.py
Traceback (most recent call last):
  File "SynthesiaKontrol-MK1.py", line 6, in <module>
    from msvcrt import getch
ModuleNotFoundError: No module named 'msvcrt'

**Comment by ojacques** [comment]
> Hello Oliver,
> Thanks so much for sharing this project. I learn about adding 3 to the command line "python 3....
> 
> I'm presently trying to figure out the following at the install the KK Light Guide python files....
> 
> Mansfields-MacBook-Pro:KompleteKontrolLightGuide-master Mansfield$ python3 SynthesiaKontrol-MK1.py
> Traceback (most recent call last):
> File "SynthesiaKontrol-MK1.py", line 6, in
> from msvcrt import getch
> ModuleNotFoundError: No module named 'msvcrt'

**Comment by ojacques** [comment]
> Thanks so much for sharing this project. I learn about adding 3 to the command line "python 3....

Congratulations on becoming a developer 🎉 🎈 !
![bitmoji](https://sdk.bitmoji.com/render/panel/0590ca28-a5f5-4b5d-8c01-8c0492cf834f-7c004006-0295-48e1-9653-7cba73126934-v1.png?transparent=1&palette=1&width=246)

(poor) joking aside, I don't know where you got the file `SynthesiaKontrol-MK1.py`. May I suggest that you download the latest, most up to date with this link?https://github.com/ojacques/SynthesiaKontrol/archive/master.zip

**Comment by basecrest** [comment]
Feeling great.....decoding the matrix next!!
My apologies, it was only when you responded that i confirmed the source of the .py files i was working with. They were from another synthesia user whom made a custom led program. Ooops!!
Many thanks. I got it to work repeatedly. I sped up my learning speed 100% upon first run through.
Many Thanks Oliver
