### ISSUE TITLE
Novation SL MK III

### ISSUE THREAD

**Issue by eyamga** [ojacques/SynthesiaKontrol#20]
Hi Jacques!

Do you think that it would be possible to make it work for the Novation SL MK III ?
I'd be willing to help if you think that porting the script is feasible ?

Eric

**Comment by ojacques** [comment]
@eyamga I did not know the Novation MK III had a light guide. I doubt the light guide is controlled the same way as the Komplete Kontrol series so a new way of controlling it will need to be added.
I don't have one, so I can't test. But if you have ideas, I'll definitely review Pull Requests against this project!
