### ISSUE TITLE
S88 MK2 Komplete Kontrol 

### ISSUE THREAD

**Issue by Downtime1989** [ojacques/SynthesiaKontrol#24]
How does one get get my keyboard to display the correct hand colour matching synthesia. seems to stay green and blue.

**Comment by ojacques** [comment]
First, there was an issue with S88 MK2, which was just fixed. Can you try the [latest release](https://github.com/ojacques/SynthesiaKontrol/releases)?

**Comment by mbuon** [comment]
Hi ojacques.
first of all let me congratulate with you for this beutiful work you have done.
I am trying to execute it in Windows 10 and followed the instructions, but my s88 keyboard does not work with its lights.
I installed last version as you suggested (1.3) but when I load the exe it does not work.
The script .exe has this output:

Connecting to Komplete Kontrol Keyboard
Opening Keyboard device...
Turn off lights for all notes
Connected to Komplete Kontrol!
Turn off lights for all notes
Opening LoopBe input port
  Found MIDI port KOMPLETE KONTROL - 1 2...
  Found MIDI port KOMPLETE KONTROL EXT - 1 3...
  Found MIDI port Komplete Kontrol DAW - 1 1...
  Found MIDI port LoopBe Internal MIDI 0...
Listening to Midi on LoopBe midi port

The configuration for synthesia is the following: 
https://user-images.githubusercontent.com/78043/123686434-17032f00-d850-11eb-92d8-0fe83659198c.png
 Unfortunately it does not work: the lights remain black.
Can you kindly help me on this configuration?
I am using windows 10, ni s88 mk2.

![image](https://user-images.githubusercontent.com/78043/123686434-17032f00-d850-11eb-92d8-0fe83659198c.png)

Thank you again for this wonderful script.
Massimo

**Comment by ojacques** [comment]
@mbuon, when you click on Music Output / LoopBe Internal Midi, please make sure that under "Use this device for" / "Key Lights", "Finger-based channel" is selected (the choice after Channel 16).

In any case, do you see the light guide lighting up when starting the application? If not, make sure Komplete Kontrol is not running.

**Comment by mbuon** [comment]
Hi thanks for the answer.
I did all these settings you are suggesting. I load the script synthesiakontrol.exe, select the s88 and  I see the lights.
![image](https://user-images.githubusercontent.com/78043/124158910-cc292780-da9a-11eb-88f7-b9e27b84a9a4.png)
In synthesia, I make these settings:
![image](https://user-images.githubusercontent.com/78043/124159047-f5e24e80-da9a-11eb-8102-2928060ef241.png)

![image](https://user-images.githubusercontent.com/78043/124158570-5d4bce80-da9a-11eb-829b-f2a107fc5903.png)
![image](https://user-images.githubusercontent.com/78043/124158615-6d63ae00-da9a-11eb-880d-ac62a5db8a3f.png)

My Komplete s88 has firmware 0.5.9
It seems not working.
Komplete kontrol si not working in backend.
Tasks related to Kontakt instrument are:
![image](https://user-images.githubusercontent.com/78043/124159462-7b65fe80-da9b-11eb-838d-067152563a17.png)
Thank you for your help
Massimo

**Comment by mbuon** [comment]
Hi, I found the reason: the LoopBe1 midi port was in "mute" state.
I clicked on the icon in the tray of windows 10 and then I clicked to unmute the port. It works fine!
Thanks for your support and maybe this could help others enjoying this beautiful application
![image](https://user-images.githubusercontent.com/78043/124168225-2333fa00-daa5-11eb-9488-5d1986080b74.png)

**Comment by ojacques** [comment]
Great, thanks for the update! I had no idea the midi port could be muted...
