### ISSUE TITLE
Support for MK1

### ISSUE THREAD

**Issue by cyberluke** [ojacques/SynthesiaKontrol#5]
Support for MK1 please? Time schedule? What is required? Can i help?

**Comment by ojacques** [comment]
@cyberluke - I just added support for MK1. I have not been able to test it though. Can you try it out and report?
Thanks!
https://github.com/ojacques/SynthesiaKontrol/releases

**Comment by frozensnowy** [comment]
Hey @ojacques - Just tested it out on my S88 MK1. Works perfectly out of the box, thus far no issues at all.

**Comment by ojacques** [comment]
Thanks for the report @frozensnowy. I'm going ahead and marking this as resolved.
