### ISSUE TITLE
Sorry, keyboard not supported yet!

### ISSUE THREAD

**Issue by Dthull** [ojacques/SynthesiaKontrol#7]
**OS:** MacOS Mojave 10.14.4
**HARDWARE:** Komplete Kontrol S61 MK2

Following error:

MacBook-Pro:SynthesiaKontrol danny$ sudo python SynthesiaKontrol.py
Select your keyboard (1,2,3,...):
  1-Komplete Kontrol S61 MK2
  2-Komplete Kontrol S88 MK2
  3-Komplete Kontrol S49 MK2
  4-Komplete Kontrol S61 MK1
  5-Komplete Kontrol S88 MK1
  6-Komplete Kontrol S49 MK1
  7-Komplete Kontrol S25 MK1

####   (  I press "1" for 1-Komplete Kontrol S61 MK2  )----> resulting with:

Sorry, keyboard not supported yet!

Any Ideas???

**Comment by ojacques** [comment]
Make sure you press the "1" key and enter. There should be no space or special character.

**Comment by audionerd** [comment]
I got this error from python 2, where `input` works differently. Does not occur when using python 3.
